#!/bin/sh

set -e

export GK_PATH=$(readlink -f ${0%/*}/..)
export GK_CONF=$GK_PATH/conf
export GK_SCRIPTS=$GK_PATH/scripts
. $GK_PATH/conf/conf

mkdir -p $GK_REPO_PATH

if [ -z $GK_USER ]; then
	echo "This shell is supposed to be executed via ssh only. You appear to not have any GitKiss username"
	exit 1
fi



# launchcommand takes only one string containing the entire command
launchCommand() {
	cmd=$1
	shift
	args=$@

	case $cmd in
		"repo")
			$GK_SCRIPTS/repo $args
			;;
		*)
			echo "Unrecognized command."
			return 1
	esac
}


interactive(){
	echo -n "$GK_PS1"
	while read line; do
		if [ "$line" = "exit" ]; then
			break
		fi
		launchCommand $line
		echo -n "$GK_PS1"
	done
	echo "exiting..."
}


if [ "$1" != "-c" ]; then
	echo "Hi, $GK_USER!"
	interactive || true
	exit 0
fi

shift

# filter out here git pull/push/clone commands

launchCommand $1
