#!/bin/sh

set -e

export GK_PATH=$(readlink -f ${0%/*}/..)
export GK_CONF=$GK_PATH/conf
export GK_SCRIPTS=$GK_PATH/scripts
. $GK_CONF/conf

mkdir -p $GK_REPO_PATH

if [ -z $GK_USER ]; then
	echo "This shell is supposed to be executed via ssh only. You appear to not have any GitKiss username" >&2
	exit 1
fi



# launchcommand takes only one string containing the entire command and, if it is valid, it executes it.
launchCommand() {
	cmd=$1
	shift
	args=$@

	case $cmd in
		"repo")
			$GK_SCRIPTS/repo $args
			;;
		*)
			echo "Unrecognized command." >&2
			return 1
	esac
}


# interactive runs the interactive shell.
interactive(){
	echo -n "$GK_PROMPT"
	while read line; do
		if [ -z "$line" ]; then
			echo -n "$GK_PROMPT"
			continue
		fi
		if [ "$line" = "exit" ]; then
			break
		fi
		if ! launchCommand $line; then
			echo -n "$GK_ERR_PROMPT"
		else
			echo -n "$GK_PROMPT"
		fi
	done
	echo "exiting..." >&2
}


if [ "$1" != "-c" ]; then
	echo "\nHi, $GK_USER!\n"
	if [ "$GK_INTERACTIVE" = "true" ]; then
		interactive
	else
		echo "You have successfully authenticated, but we don't provide interactive shell access.\n"
	fi
	exit 0
fi

shift

# filter out here git pull/push/clone commands

launchCommand $1
