#!/bin/sh

set -e

export GK_PATH=$(readlink -f ${0%/*}/..)
export GK_CONF=$GK_PATH/conf
export GK_SCRIPTS=$GK_PATH/scripts
. $GK_PATH/conf/conf

mkdir -p $GK_REPO_PATH

if [ -z $GK_USER ]; then
	echo "This shell is supposed to be executed via ssh only. You appear to not have any GitKiss username"
	exit 1
fi

if [ "$1" != "-c" ]; then
	echo "Hi, $GK_USER, you have successfully authenticated but we don't provide interactive shell access at the moment."
	exit 0
fi

shift



# launchcommand takes only one string containing the entire command
launchcommand() {
	cmd=$1
	shift
	args=$@

	case $cmd
		in "repo")
			$GK_SCRIPTS/repo $args
			;;
	esac
}

launchcommand $1
